AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Shapeshifter reader'

Parameters:
  RepoName:
    Type: String

Resources:
  DockerRegistry:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepoName
      ImageScanningConfiguration:
        scanOnPush: "true"
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
            {
              "rulePriority": 1,
              "description": "Keep last 5 images",
              "selection": {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 5
              },
              "action": { "type": "expire" }
            }]
          }
  #      RepositoryPolicyText: Json