AWSTemplateFormatVersion: 2010-09-09
Description: Fargate stack

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  ContainerSecurityGroup:
    Type: String
  TaskName:
    Type: String
  Image:
    Type: String
  PrivateSubnetIdA:
    Type: String
  PrivateSubnetIdB:
    Type: String
  PrivateSubnetIdC:
    Type: String
  EcsTargetGroup:
    Type: String

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: 'SHAPESHIFTER-CLUSTER'

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${TaskName}'

  EcsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'SHAPESHIFTER-ECS-ROLE'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${TaskName}-TASK-ROLE'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'

  ShapeshifterDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroup
    Properties:
      Family: !Ref TaskName
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 0.5GB
      ExecutionRoleArn: !Ref EcsRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Ref TaskName
          Image: !Ref Image
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs

  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: 'SHAPESHIFTER-SERVICE'
      Cluster: !Ref Cluster
      TaskDefinition: !Ref ShapeshifterDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 30
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !Ref PrivateSubnetIdA
            - !Ref PrivateSubnetIdB
            - !Ref PrivateSubnetIdC
          SecurityGroups:
            - !Ref ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: !Ref TaskName
          ContainerPort: 8080
          TargetGroupArn: !Ref EcsTargetGroup