AWSTemplateFormatVersion: 2010-09-09
Description: Load balancing stack

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  LoadBalancerSecurityGroup:
    Type: String
  PublicSubnetIdA:
    Type: String
  PublicSubnetIdB:
    Type: String
  PublicSubnetIdC:
    Type: String
  DockerLambdaArn:
    Type: String

Resources:

  AppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: 'SHAPESHIFTER-ALB'
      Scheme: 'internet-facing'
      Subnets:
        - !Ref PublicSubnetIdA
        - !Ref PublicSubnetIdB
        - !Ref PublicSubnetIdC
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Tags:
        - Key: "Name"
          Value: 'SHAPESHIFTER-ALB'

  ListenerHttp:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref AppLoadBalancer
      Port: 8080
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref LambdaTargetGroup

  WeightedListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref LambdaTargetGroup
                Weight: 1
              - TargetGroupArn: !Ref EcsTargetGroup
                Weight: 1
      Conditions:
        - Field: path-pattern
          Values:
            - '*'
      ListenerArn: !Ref ListenerHttp
      Priority: 1

  ElbLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DockerLambdaArn
      Action: lambda:InvokeFunction
      Principal: elasticloadbalancing.amazonaws.com
      SourceArn: !Sub 'arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:targetgroup/SHAPESHIFTER-TG-LAMBDA/*'

  LambdaTargetGroup:
    DependsOn: ElbLambdaInvokePermission
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: 'SHAPESHIFTER-TG-LAMBDA'
      TargetType: lambda
      Targets:
        - Id: !Ref DockerLambdaArn

  EcsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: '/'
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      Name: !Sub 'SHAPESHIFTER-TG-ECS'
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId

Outputs:
  LoadBalancer:
    Value: !Ref AppLoadBalancer
  EcsTargetGroup:
    Value: !Ref EcsTargetGroup